[versions]
kotlin = "2.3.0-Beta2"
mcp = "0.7.6"
ktor = "3.3.2"
kotlinxSerialization = "1.9.0"
xemanticMdc = "0.1.1"
dockerJavaBom = "3.6.0"
postgresql = "42.7.8"
logback = "1.5.20"
gradle-buildconfig = "5.7.1"
jooq = "3.20.8"
flyway = "11.16.0"
hikari = "7.0.2"
pgvector = "0.1.6"
pdfbox = "3.0.3"

[libraries]
modelcontextprotocol-kotlin-sdk = { module = "io.modelcontextprotocol:kotlin-sdk", version.ref = "mcp" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-java = { module = "io.ktor:ktor-client-java" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
xemantic-ai-tool-schema-mdc = { module = "com.xemantic.ai:xemantic-ai-tool-schema-mdc", version.ref = "xemanticMdc" }
docker-java = { module = "com.github.docker-java:docker-java" }
docker-java-bom = { module = "com.github.docker-java:docker-java-bom", version.ref = "dockerJavaBom" }
docker-java-transport-httpclient5 = { module = "com.github.docker-java:docker-java-transport-httpclient5" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
pgvector = { module = "com.pgvector:pgvector", version.ref = "pgvector" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradle-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "gradle-buildconfig" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }